import { NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { createClient } from '@supabase/supabase-js';
import { slugify } from '@/lib/blog/slug';
import { estimateReadingTime } from '@/lib/blog/mdx';

// Vercel Cron will call this daily. Guarded by CRON_SECRET so it can't be
// triggered by outsiders. Never uses the anon key — this always writes as
// service role, so drafts land as pending_review without a real user id.

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

const RESEARCH_PROMPT = `You are the Inovers Journal daily research assistant.

Every day, propose ONE piece of long-form writing that Inovers.io should publish.
Topic universe (pick ONE per run, rotate over time):
- Innovation: an under-covered recent invention that changes the future
- Creative thinking: how it really works, and how it fails
- The need for innovative thinking (in India specifically)
- The need for creative thinking (in India specifically)
- How to develop innovative thinking in children — practical, not woolly
- How to develop creative thinking in children — practical, not woolly
- AI vs innovative thinking: where they compete, cooperate, or replace
- The Indian schooling system: what it teaches, what it kills, what to change
- Under-taught history of ideas: a thinker or invention students never hear about

Constraints on the piece you draft:
- Voice: strong, well-argued, sometimes counter-intuitive. Civil. Never rage-bait.
- Evidence: cite at least three real, verifiable sources (books, papers,
  reputable articles, actual events). Include a "Sources" section with links.
- Length: 900–1400 words.
- Structure: a hooky lede paragraph, 3–5 H2 sections, ends with a short call
  to think or act.
- Audience: Indian readers primary, global readers secondary. Use Indian
  examples where they land better than global ones.
- No hallucinated statistics. If you're not sure, say so.

Output STRICTLY as JSON with this shape and nothing else:

{
  "title": "string",
  "dek": "one-sentence subtitle, plain, no hype",
  "tags": ["one-to-three tag slugs from: innovation, creative-thinking, education, children, ai, bharat, history, methods"],
  "body_mdx": "the full article in Markdown/MDX",
  "sources": [
    {"title": "string", "url": "https://..."},
    ...
  ],
  "editor_notes": "2–4 sentences on what YOU are unsure about — hallucination checks the human editor should run before publishing.",
  "confidence": "low | medium | high"
}
`;

interface DraftPayload {
  title: string;
  dek: string;
  tags: string[];
  body_mdx: string;
  sources: { title: string; url: string }[];
  editor_notes: string;
  confidence: 'low' | 'medium' | 'high';
}

function guardCronSecret(req: Request): boolean {
  const header = req.headers.get('authorization') || '';
  const secret = process.env.CRON_SECRET || '';
  if (!secret) return false;
  return header === `Bearer ${secret}`;
}

export async function GET(req: Request) {
  if (!guardCronSecret(req)) {
    return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!apiKey || !supabaseUrl || !serviceKey) {
    return NextResponse.json({ error: 'missing_env' }, { status: 500 });
  }

  const anthropic = new Anthropic({ apiKey });
  const model = 'claude-sonnet-5';

  const result = await anthropic.messages.create({
    model,
    max_tokens: 4000,
    messages: [
      {
        role: 'user',
        content: RESEARCH_PROMPT,
      },
    ],
  });

  const raw = result.content
    .filter((c): c is { type: 'text'; text: string } => c.type === 'text')
    .map((c) => c.text)
    .join('\n')
    .trim();

  const payload = extractJson<DraftPayload>(raw);
  if (!payload) {
    return NextResponse.json({ error: 'model_output_unparseable', raw: raw.slice(0, 400) }, { status: 502 });
  }

  const supabase = createClient(supabaseUrl, serviceKey);

  const slug = await uniqueSlug(supabase, slugify(payload.title));
  const readingTime = estimateReadingTime(payload.body_mdx);

  const { data: post, error } = await supabase
    .from('blog_posts')
    .insert({
      slug,
      title: payload.title,
      dek: payload.dek,
      body_mdx: appendSources(payload.body_mdx, payload.sources),
      reading_time: readingTime,
      status: 'pending_review',
      source_note: `Generated by daily-research bot on ${new Date().toISOString().slice(0, 10)} — model=${model}, confidence=${payload.confidence}`,
      research_json: payload as unknown as object,
      editor_notes: payload.editor_notes,
    })
    .select('id, slug')
    .single();

  if (error) {
    return NextResponse.json({ error: 'insert_failed', message: error.message }, { status: 500 });
  }

  // Attach tags (ignore unknown slugs).
  const validTags = payload.tags.filter((t) => typeof t === 'string' && t.length > 0);
  if (validTags.length && post) {
    await supabase.from('blog_post_tags').upsert(
      validTags.map((t) => ({ post_id: post.id, tag_slug: t })),
      { onConflict: 'post_id,tag_slug' }
    );
  }

  return NextResponse.json({ ok: true, draft_id: post?.id, slug: post?.slug });
}

function extractJson<T>(raw: string): T | null {
  // Model sometimes wraps in ```json fences — strip them.
  const cleaned = raw.replace(/^```(?:json)?/i, '').replace(/```$/, '').trim();
  try {
    return JSON.parse(cleaned) as T;
  } catch {
    // Try to find the first { ... last } pair.
    const start = cleaned.indexOf('{');
    const end = cleaned.lastIndexOf('}');
    if (start === -1 || end === -1) return null;
    try {
      return JSON.parse(cleaned.slice(start, end + 1)) as T;
    } catch {
      return null;
    }
  }
}

function appendSources(body: string, sources: DraftPayload['sources']): string {
  if (!sources?.length) return body;
  const lines = [
    '',
    '---',
    '',
    '## Sources',
    '',
    ...sources.map((s) => `- [${s.title}](${s.url})`),
  ];
  return body.trim() + '\n' + lines.join('\n') + '\n';
}

async function uniqueSlug(
  supabase: ReturnType<typeof createClient>,
  base: string
): Promise<string> {
  let candidate = base || `post-${Date.now()}`;
  for (let i = 0; i < 20; i += 1) {
    const { data } = await supabase
      .from('blog_posts')
      .select('id')
      .eq('slug', candidate)
      .maybeSingle();
    if (!data) return candidate;
    candidate = `${base}-${i + 2}`;
  }
  return `${base}-${Date.now()}`;
}
