-- =====================================================================
-- Inovers Blog — Schema (additive to existing inovers-web schema)
-- Run in Supabase SQL Editor AFTER the existing waitlist/ideas schema.
-- Safe to re-run (idempotent).
-- =====================================================================

create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";  -- fuzzy search over titles

-- 1. Extend profiles with a role column ------------------------------------
--    reader (default) — can read posts, must sign in to comment
--    author           — can be attributed as post author
--    editor           — can review draft queue and publish
--    admin            — everything, including moderation + deletes
do $$ begin
  create type user_role as enum ('reader','author','editor','admin');
exception when duplicate_object then null; end $$;

alter table public.profiles
  add column if not exists role user_role not null default 'reader';

-- Backfill an initial admin: change the email below to yours before running,
-- or run this manually once you know your uid.
-- update public.profiles set role = 'admin'
--   where id = (select id from auth.users where email = 'you@inovers.in');

-- 2. Post status enum -----------------------------------------------------
do $$ begin
  create type post_status as enum (
    'draft',            -- author is still writing
    'pending_review',   -- ready for editor (also used by daily-research bot)
    'scheduled',        -- approved, waiting for publish_at
    'published',        -- live
    'archived'          -- pulled from public list, still reachable by slug
  );
exception when duplicate_object then null; end $$;

-- 3. Tags -----------------------------------------------------------------
create table if not exists public.blog_tags (
  slug        text primary key,           -- kebab-case, url-safe
  label       text not null,
  description text,
  created_at  timestamptz not null default now()
);

-- Seed the taxonomy. Kept small on purpose — big tag clouds dilute SEO.
insert into public.blog_tags (slug, label, description) values
  ('innovation',       'Innovation',              'Recent innovations, the mindset behind them, and what they change.'),
  ('creative-thinking','Creative Thinking',       'How ideas actually form. What blocks them. How to unblock.'),
  ('education',        'Education',               'What the schooling system gets right, wrong, and refuses to fix.'),
  ('children',         'Kids & Learning',         'Raising and teaching children who can think for themselves.'),
  ('ai',               'AI & Human Thinking',     'Where AI helps thinking, where it replaces it, and what to do about it.'),
  ('bharat',           'Bharat',                  'Innovation, science and craft as it plays out in India.'),
  ('history',          'History of Ideas',        'Inventions and thinkers that changed the future — and why.'),
  ('methods',          'Thinking Methods',        'First principles, constraints, analogies, prototyping — how the best thinkers work.')
on conflict (slug) do nothing;

-- 4. Posts ---------------------------------------------------------------
create table if not exists public.blog_posts (
  id             uuid primary key default gen_random_uuid(),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  publish_at     timestamptz,
  status         post_status not null default 'draft',

  slug           text not null unique,
  title          text not null,
  dek            text,                    -- subtitle / one-liner, shown on cards
  cover_image    text,                    -- URL, may be null
  reading_time   integer,                 -- minutes, computed by author or by mdx pipeline

  -- Content is MDX. We store raw source; render at request time.
  body_mdx       text not null,
  body_excerpt   text,                    -- first 240 chars for lists + OG

  -- Author. Nullable so bot drafts (author_id null) can exist before an editor claims one.
  author_id      uuid references public.profiles(id) on delete set null,
  author_name    text,                    -- snapshot at publish; survives profile changes
  author_avatar  text,

  -- Editorial trail
  source_note    text,                    -- e.g. "Generated by daily-research bot 2026-07-05"
  research_json  jsonb,                   -- structured research payload for editor review
  editor_id      uuid references public.profiles(id) on delete set null,
  editor_notes   text,

  -- Denormalized counters (kept fresh by triggers below)
  comment_count  integer not null default 0,
  reaction_count integer not null default 0,
  view_count     integer not null default 0
);

create index if not exists blog_posts_status_publish_at_idx
  on public.blog_posts (status, publish_at desc);
create index if not exists blog_posts_publish_at_idx
  on public.blog_posts (publish_at desc)
  where status = 'published';
create index if not exists blog_posts_title_trgm_idx
  on public.blog_posts using gin (title gin_trgm_ops);

-- 5. Post ↔ Tag ----------------------------------------------------------
create table if not exists public.blog_post_tags (
  post_id  uuid not null references public.blog_posts(id) on delete cascade,
  tag_slug text not null references public.blog_tags(slug) on delete restrict,
  primary key (post_id, tag_slug)
);
create index if not exists blog_post_tags_tag_idx on public.blog_post_tags (tag_slug);

-- 6. Comments (threaded ONE level: post → top comment → replies) ---------
create table if not exists public.blog_comments (
  id           uuid primary key default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  edited_at    timestamptz,
  post_id      uuid not null references public.blog_posts(id) on delete cascade,
  author_id    uuid not null references public.profiles(id) on delete cascade,
  parent_id    uuid references public.blog_comments(id) on delete cascade,
  body         text not null check (length(trim(body)) between 2 and 4000),
  is_deleted   boolean not null default false,
  is_hidden    boolean not null default false,     -- by moderator
  reaction_count integer not null default 0,
  report_count   integer not null default 0
);
create index if not exists blog_comments_post_idx on public.blog_comments (post_id, created_at);
create index if not exists blog_comments_parent_idx on public.blog_comments (parent_id);
create index if not exists blog_comments_author_idx on public.blog_comments (author_id);

-- 7. Reactions (👍 style — one per user per target) ----------------------
--    Target is either a post OR a comment. XOR enforced by check.
do $$ begin
  create type reaction_kind as enum ('up','insightful','curious','disagree');
exception when duplicate_object then null; end $$;

create table if not exists public.blog_reactions (
  id           uuid primary key default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  user_id      uuid not null references public.profiles(id) on delete cascade,
  post_id      uuid references public.blog_posts(id) on delete cascade,
  comment_id   uuid references public.blog_comments(id) on delete cascade,
  kind         reaction_kind not null default 'up',
  check ((post_id is not null)::int + (comment_id is not null)::int = 1)
);
create unique index if not exists blog_reactions_post_uniq
  on public.blog_reactions (user_id, post_id) where post_id is not null;
create unique index if not exists blog_reactions_comment_uniq
  on public.blog_reactions (user_id, comment_id) where comment_id is not null;

-- 8. Reports (any signed-in user can flag; editors triage) ---------------
do $$ begin
  create type report_reason as enum ('spam','harassment','misinfo','off_topic','other');
  create type report_status as enum ('open','dismissed','actioned');
exception when duplicate_object then null; end $$;

create table if not exists public.blog_reports (
  id           uuid primary key default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  reporter_id  uuid not null references public.profiles(id) on delete cascade,
  post_id      uuid references public.blog_posts(id) on delete cascade,
  comment_id   uuid references public.blog_comments(id) on delete cascade,
  reason       report_reason not null,
  note         text,
  status       report_status not null default 'open',
  resolved_by  uuid references public.profiles(id) on delete set null,
  resolved_at  timestamptz,
  check ((post_id is not null)::int + (comment_id is not null)::int = 1)
);
create index if not exists blog_reports_open_idx on public.blog_reports (status, created_at)
  where status = 'open';

-- 9. Views tracking (very rough — one row per (post, day, user or ip hash))
create table if not exists public.blog_post_views (
  post_id     uuid not null references public.blog_posts(id) on delete cascade,
  day         date not null default (now() at time zone 'utc')::date,
  visitor_key text not null,   -- user_id::text OR sha256(ip + ua)
  primary key (post_id, day, visitor_key)
);

-- 10. Triggers -----------------------------------------------------------

-- 10a. updated_at maintenance
create or replace function public.tg_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists blog_posts_touch on public.blog_posts;
create trigger blog_posts_touch
  before update on public.blog_posts
  for each row execute function public.tg_touch_updated_at();

-- 10b. comment_count on posts
create or replace function public.tg_blog_comment_count()
returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    if new.is_deleted = false and new.is_hidden = false then
      update public.blog_posts
        set comment_count = comment_count + 1
        where id = new.post_id;
    end if;
  elsif tg_op = 'DELETE' then
    if old.is_deleted = false and old.is_hidden = false then
      update public.blog_posts
        set comment_count = greatest(comment_count - 1, 0)
        where id = old.post_id;
    end if;
  elsif tg_op = 'UPDATE' then
    -- Soft delete or hide should decrement; restore should increment.
    if (old.is_deleted = false and old.is_hidden = false)
       and (new.is_deleted = true or new.is_hidden = true) then
      update public.blog_posts set comment_count = greatest(comment_count - 1, 0)
        where id = new.post_id;
    elsif (old.is_deleted = true or old.is_hidden = true)
       and (new.is_deleted = false and new.is_hidden = false) then
      update public.blog_posts set comment_count = comment_count + 1
        where id = new.post_id;
    end if;
  end if;
  return null;
end $$;

drop trigger if exists blog_comments_count on public.blog_comments;
create trigger blog_comments_count
  after insert or update or delete on public.blog_comments
  for each row execute function public.tg_blog_comment_count();

-- 10c. reaction_count on post/comment
create or replace function public.tg_blog_reaction_count()
returns trigger language plpgsql as $$
declare
  delta integer;
begin
  delta := case when tg_op = 'INSERT' then 1 when tg_op = 'DELETE' then -1 else 0 end;
  if tg_op = 'INSERT' then
    if new.post_id is not null then
      update public.blog_posts set reaction_count = reaction_count + delta where id = new.post_id;
    else
      update public.blog_comments set reaction_count = reaction_count + delta where id = new.comment_id;
    end if;
  elsif tg_op = 'DELETE' then
    if old.post_id is not null then
      update public.blog_posts set reaction_count = greatest(reaction_count + delta, 0) where id = old.post_id;
    else
      update public.blog_comments set reaction_count = greatest(reaction_count + delta, 0) where id = old.comment_id;
    end if;
  end if;
  return null;
end $$;

drop trigger if exists blog_reactions_count on public.blog_reactions;
create trigger blog_reactions_count
  after insert or delete on public.blog_reactions
  for each row execute function public.tg_blog_reaction_count();

-- 10d. report_count on comment (auto-hide at 3 open reports; editor can restore)
create or replace function public.tg_blog_report_count()
returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' and new.comment_id is not null then
    update public.blog_comments
      set report_count = report_count + 1,
          is_hidden = case when report_count + 1 >= 3 then true else is_hidden end
      where id = new.comment_id;
  end if;
  return null;
end $$;

drop trigger if exists blog_reports_count on public.blog_reports;
create trigger blog_reports_count
  after insert on public.blog_reports
  for each row execute function public.tg_blog_report_count();

-- 10e. Snapshot author info on publish (so profile edits don't rewrite history)
create or replace function public.tg_blog_snapshot_author()
returns trigger language plpgsql as $$
declare
  p public.profiles%rowtype;
begin
  if new.status = 'published' and (old.status is null or old.status != 'published') then
    if new.publish_at is null then new.publish_at := now(); end if;
    if new.author_id is not null then
      select * into p from public.profiles where id = new.author_id;
      if found then
        if new.author_name  is null then new.author_name  := p.name; end if;
        if new.author_avatar is null then new.author_avatar := p.avatar_url; end if;
      end if;
    end if;
    -- Build a short excerpt if the author didn't set one.
    if new.body_excerpt is null and new.body_mdx is not null then
      new.body_excerpt := substr(regexp_replace(new.body_mdx, '\s+', ' ', 'g'), 1, 240);
    end if;
  end if;
  return new;
end $$;

drop trigger if exists blog_posts_snapshot on public.blog_posts;
create trigger blog_posts_snapshot
  before insert or update on public.blog_posts
  for each row execute function public.tg_blog_snapshot_author();

-- 11. Convenience view: published posts joined with tag list --------------
create or replace view public.blog_posts_public as
select
  p.id, p.slug, p.title, p.dek, p.cover_image, p.reading_time,
  p.body_excerpt, p.author_name, p.author_avatar,
  p.publish_at, p.comment_count, p.reaction_count, p.view_count,
  coalesce(
    (select array_agg(tag_slug order by tag_slug)
       from public.blog_post_tags where post_id = p.id),
    '{}'::text[]
  ) as tags
from public.blog_posts p
where p.status = 'published' and p.publish_at <= now();

-- Grant read on the view to anon so the landing page can render without login.
grant select on public.blog_posts_public to anon, authenticated;
grant select on public.blog_tags        to anon, authenticated;

-- =====================================================================
-- End of 001_blog_schema.sql
-- =====================================================================
